dq_fun = @difeq_IPS_PID;
tspan = [0:0.01:5];
z0 = [1;0;pi/3;0;0];
m = 0.1;
M = 2;
l = 0.5;
g = 9.8;
A = [0,1,0,0;
    0,0,-m*g/M,0;
    0,0,0,1;
    0,0,(m+M)*g/(M*l),0];
B = [0;1/M;0;-1/(M*l)];
Kp = 100;
Kd = 20;
Ki = 70;
[t,z] = ode45(dq_fun,tspan,z0,[],A,B,Kp,Kd,Ki);
plot(t,z(:,1),'-r','linewidth',2);
hold on;
plot(t,z(:,2),'-y','linewidth',2);
hold on;
plot(t,z(:,3),'-g','linewidth',2);
hold on;
plot(t,z(:,4),'-b','linewidth',2);
hold on;
legend('x','xdot','theta','thetadot');
xlabel('Time');
ylabel('Displacement');
title('Displacements of Linearized Inverted Pendulum System with PID Controller');
grid on;
grid minor;