dq_fun = @difeq_IPS_Observer_nonlinear;
tspan = [0:0.01:1];
z0 = [1;0;pi/3;0;1;0;pi/3;0];
m = 0.1;
M = 2;
l = 0.5;
g = 9.8;
P_Con = [-3+1i,-3-1i,-2+3j,-2-3j];
P_Ob = 6 * P_Con;
A = [0,1,0,0;
    0,0,-m*g/M,0;
    0,0,0,1;
    0,0,(m+M)*g/(M*l),0];
B = [0;1/M;0;-1/(M*l)];
C = [1,0,0,0;0,0,1,0];
K = place(A,B,P_Con);
L = place(A',C',P_Ob)';
A_bar = [A-B*K,B*K;
         zeros(size(A)),A-L*C];
[t,z] = ode45(dq_fun,tspan,z0,[],m,M,g,l,K,L,C);
plot(t,z(:,1),'-r','linewidth',2);
hold on;
plot(t,z(:,2),'-y','linewidth',2);
hold on;
plot(t,z(:,3),'-g','linewidth',2);
hold on;
plot(t,z(:,4),'-b','linewidth',2);
hold on;
legend('x','xdot','theta','thetadot');
xlabel('Time');
ylabel('Displacement');
title('Displacements of Nonlinear Inverted Pendulum System with Observer');
grid on;
grid minor;